# Generated by Django 4.2.26 on 2025-11-27 19:16

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PageGenerationTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('base_name', models.CharField(help_text='Base name for generated pages', max_length=100)),
                ('count', models.PositiveIntegerField(help_text='Number of pages to generate')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('total_time_seconds', models.FloatField(blank=True, null=True)),
                ('avg_time_per_page', models.FloatField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PerformanceMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('metric_name', models.CharField(max_length=100)),
                ('value', models.FloatField()),
                ('unit', models.CharField(default='seconds', max_length=20)),
                ('browser', models.CharField(default='chrome', max_length=50)),
                ('headless', models.BooleanField(default=True)),
                ('parallel_workers', models.PositiveIntegerField(default=1)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='pages.pagegenerationtask')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='GeneratedPage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('sequence_number', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('creating', 'Creating'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('page_url', models.URLField(blank=True)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.FloatField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='pages.pagegenerationtask')),
            ],
            options={
                'ordering': ['task', 'sequence_number'],
            },
        ),
    ]
